sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product ittn-010
env:
  global:
    -
      # LTD_AWS_ID
      secure: GViHwc2avk5GwPgUULSl4dQ9dvEhDFzfkOre50bqWo14l4suC7lQvKyGTX3sNOoHhevhDDN+4H9AvBtG+/kfxPv96QqoMQdyreNJBHEkv54HTLUU+vxWCq3qZdSiXMHDA0SBDxsDXqj+x2HWD+5XOcSPJPDdjhSFwsfzhsR0UkAEEoCJM1HqHmJUONfXeb7fzkKB8ZKugVf/fQZCRjIzQMpiJwsm3aFaVgd9oEwaXkug/0kNj0bLtxUD+AqNVmXpDuK2XPVHUvJ8Z04QzD8eB1aKQMlO1ZLygYTFHvjnQCsv+fHxCIZgSI9/3Q3FKnz5K17Rg8eo059rXOZtroOmP3h62EHZUbcKprI1ER1kR1NuajKQP46zBVMcgMNOzJ7rAGV2WZA836GY+BHuWnK+nG7ZiaISwq8yjZ5xwrkAm+C7MLJYI53d67dxD+cmkMlDnGApfDufYIEpyJJKmZ9kFux0+YwUklaJx0EePAv6tgKqEiY8UQMbyxX32vfyXrv8FCGBTbKdgDoqINs3HO/N8xbhyP0AGBYwBOCn+HxwCpRzv5h8EdOdKrDG2OsD2TA+YXhJh9VZXWFxS4heaNOrRb/EPm65f4HvSjqgZvjIt1X4vbrg/tDzt/i7x1uUfwCrhQPMOXuf6gARF7kWbNhaVEI7G2TX53KAM+jJh2Fno6A=
    -
      # LTD_AWS_SECRET
      secure: WtTVoOgoexYCW0h2qxL50lFfzqIlHTayxv5R5uSHdN8Oqmkno61tVDnEjuz0h5B26PO/k4pnVjVPEzI+VSbkaWe4+dD+jjk+z8I6HplGMszojwtJg3fdKSBK9CSJmN6x7HDe3mHULRh8eMuizV6Eg6uHpQoC5pcOnb5Gp8fcBdcWtN1mhp8fl4DtLpxqDXMiWZWHO/saM/cAMS5m6BowIIw4Rjzgrl7NvROdv2cyKiOmeCc1I82CepRSDh90Jb0oNJuGmRHOJNPSgfOnXeHTGqOHZkrMLnLxONXCi097465NkqROlyyAwWN2T6idqqgjt1aBtYIE/W019qnDhPl4w5ZVxuEwYLQZCbwtS9aRDZZj19jgXcCHrkKn7RtIYeXTGaRgRO5eBu128rnyfMACbrkmiT9sNa4JsRLoWs1ads3ls2JxbI24GFwhDOBTZMrvBQf+kis3yjTeM+BGoWjcqvuXYa2snZ2MO4xtNeuEHgOdI9HTbDSMrs7b5ymU+GiKGaiey9svxRYDurql66Fc/TzKBHvPGKicbeGKhR9Y+cnUsQxNIVEG2QhF/Wz92Ox1bu9v0jes5DMxzNjNYkWPRPcBHoH0UfmIe+hNVl+L+h954m/UNYexStRaqHeEIhhN/v0sprocT16QMY4Ji7JHVyDA2tVAdmoSIZXR4Pch5Rc=
    -
      # LTD_USERNAME
      secure: Zs23nWy1Qj1BZmWmZlAe11CWMPRe3WyU9A/SqcwRLugEc9r8050BD59kzlNxH4b87dwNDL/0+3xKfGNk3axzXOvjOzpu7MsWPBpElPJAe5F14b9BEJfmQY3VcPcBBbfgBd8D27ZJajkd/LT0TufEnRcZcav1iWxUaDuZG1uST7uYuHeRhR/nnqPYNB9IYsH3ekBewTnUBpoPqMRtQRL+Fr6lYaCQapvc3xAqBcCJkEIEknZBbukJGmyuG73briqh5PFIJC2ukZxz6iei8+iTKUxUdOBIpXerBGo7sPUqps5Si6dGDTxzZ8s2UAT5rOGZzLndzTQVOVOFbT44uI+5PiFWGZZ7Mzbtz5rjw4fIiHUqtPWdfWnVXfrdiDjzHqfrd4HbNOA0w+okVdmMaF5rXGdMx3yp0zJmQ8UFM6xM48qj/eMzkalqJzYO3e4HW1nQLrqpNuLl3aLJtJpjaOJ4cUhXWzdAoA+ZBYz5/MVYI6xedeUDw5pxXMIgpgRZX3fyQEDF2aPoc8APBQyqh+0O6/lyNmx/qhCmu5K8o76GKnI7jPFPKdx3EU9g6qRGjSgtrTaNI8PNbRL9xiNu13nyaiXVx+vbjBN36fMmGZavWD5LFQpTFd+dphK0N6yMyAp5uzYW87kFnYghvWT6kUXrqBCquJbrf2vf6O5mVpOEFFc=
    -
      # LTD_PASSWORD
      secure: OHzxrP6gorjXfyUTKylTVbNT5MFdKp7R1Pa2NWZmgOivg8hrCIh8pAjoZlHE6l4FrspTD16Jps6wUHc8k6G/ocvei0hmenXjJo035Fk8NbPqTh5B5V4kZeaMDam9pdAaoU0zP0ssh9aUYBW/HCsIu7hMd0UJ3XEIImvlqXtkTtn7zVOlO2KyLzQWwQMAXF5z51iTXFH4AmnVguMY+h8IGKf/XNvq/Q9U94wnPZ3pGbxAlL6dT7DTG99czX9THc7QFCEXrYt/TOHtEOouiikk63NtI/bHZVxatujnBxdOrXXxEO43P8BDxNSJMERt0uktWvXmySV3evVYTpnAd5t3jI7nLrEerJ+jQ/KO5WotSukXD0q6QmvFki0TG+bocIXjumpbr5EcbBrsPpbt+BpxnilnTJVlfiaSANEwl5c59SVn4MK1VfRoTWYIhhfJYGYzITEm/VseZK6JiFxxGPg9bA2pnI7Gz4FEWnV+YWEEpS7XNOPSMJKPjC1r0PHVhe2HGF9YHA39lUs3AuNgfwkfK70PWfH5jvmqaRT3nl+uB4IWd9uLwB0BtoQa9SCpVujNbbhMdaUUrB9JKJuCJHMIRzWRmENm/RKIXZ9uQ47D9PgitBRyrz+OAmXettTeusYMY2XhKvOf9eckYwKpg87tjuRGXI+kO9xAu/Na9c9wfVg=
